# Generated by Django 4.2 on 2025-12-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='guestbook',
            name='created',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
